window.opacity = 0.8

[colors.normal]
black = "#3f3f3f"
blue = "#506080"
cyan = "#8cd0d8"
green = "#60b47a"
magenta = "#dc9cc3"
red = "#b06060"
white = "#ffffff"
yellow = "#dfaf8f"

[colors.primary]
background = "#000000"
foreground = "#e0e0e0"

[env]
XTERM = "xterm-256-color"

[font]
size = 9.5

